import {RULES,DIRECTIONS,makeState,advance,allowed,routeForFrame,trimRoute,pointAt} from './engine.mjs';
const $=s=>document.querySelector(s),cfg=window.GAJWA_CONFIG||{},game=$('#game'),canvas=$('#board'),ctx=canvas.getContext('2d');
let state=makeState(),previous=state,profile=null,queued=null,progress=1,startedAt=0,lastFrame=0,best=null,runId='',audio=null,sound=false,rankScope='all',requestEpoch=0,rankingBusy=false;
const pending=new Map(),submitting=new Set();let sequence=0;
const statuses={ready:'준비',running:'플레이 중',collision:'게임 종료',win:'완주',aborted:'중도 종료'};
for(let i=1;i<=30;i++){for(const selector of ['#class-no','#rank-class']){const o=document.createElement('option');o.value=String(i);o.textContent=i+'반';$(selector).appendChild(o);}}
function resizeCanvas(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=680*dpr;canvas.height=600*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function setSave(text,type=''){const el=$('#save-state');el.textContent=text;el.className=type;}
function overlay(kicker,title,description,button){$('#overlay').hidden=false;$('#overlay-kicker').textContent=kicker;$('#overlay-title').textContent=title;$('#overlay-description').textContent=description;$('#play').textContent=button;$('#play').disabled=!profile;}
function drawApple(food,scale=1){if(!food||scale<=0)return;const x=(food.x+.5)*40,y=(food.y+.5)*40;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#739d3325';ctx.beginPath();ctx.ellipse(1,15,14,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ed5144';ctx.beginPath();ctx.moveTo(0,-10);ctx.bezierCurveTo(-20,-20,-19,16,-1,17);ctx.bezierCurveTo(19,18,20,-20,0,-10);ctx.fill();ctx.fillStyle='#ff8a7355';ctx.beginPath();ctx.ellipse(-6,-4,3,6,.3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#725b28';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(2,-18);ctx.stroke();ctx.fillStyle='#55872f';ctx.beginPath();ctx.ellipse(8,-15,7,3,-.4,0,Math.PI*2);ctx.fill();ctx.restore();}
function strokeRoute(points,width,color){ctx.beginPath();for(let i=0;i<points.length;i++){const p=points[i],x=(p.x+.5)*40,y=(p.y+.5)*40;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
function draw(alpha=progress){ctx.clearRect(0,0,680,600);for(let y=0;y<15;y++)for(let x=0;x<17;x++){ctx.fillStyle=(x+y)%2?'#a2d149':'#aad751';ctx.fillRect(x*40,y*40,40,40);}if(state.ate&&state.mode==='running'){drawApple(previous.food,1-alpha*.8);if(alpha>.7)drawApple(state.food,Math.min(1,(alpha-.7)/.3));}else drawApple(state.food);const route=routeForFrame(previous,state,alpha);const bodyEnd=Math.max(.05,route.length-.5);strokeRoute(trimRoute(route.points,bodyEnd),27,'#416de4');const tailSteps=18;for(let i=0;i<tailSteps;i++){const a=bodyEnd+i*.5/tailSteps,b=bodyEnd+(i+1)*.5/tailSteps;strokeRoute([pointAt(route.points,a),pointAt(route.points,b)],Math.max(1.4,27*(1-i/tailSteps)), '#416de4');}const h=route.head,d=route.direction;const hx=(h.x+.5)*40,hy=(h.y+.5)*40;ctx.fillStyle='#416de4';ctx.beginPath();ctx.arc(hx,hy,14.5,0,Math.PI*2);ctx.fill();for(const side of [-1,1]){const ex=hx+d.x*7-d.y*side*8,ey=hy+d.y*7+d.x*side*8;ctx.fillStyle='#f9fcff';ctx.beginPath();ctx.ellipse(ex,ey,6.1,6.7,Math.atan2(d.y,d.x),0,Math.PI*2);ctx.fill();ctx.fillStyle='#263b7c';ctx.beginPath();ctx.arc(ex+d.x*2,ey+d.y*2,3.2,0,Math.PI*2);ctx.fill();}if(state.mode==='collision'){ctx.fillStyle='#e8514333';ctx.beginPath();ctx.arc(hx,hy,24,0,Math.PI*2);ctx.fill();}$('#score').textContent=state.score;$('#game-state').textContent=statuses[state.mode]||'준비';}
function tone(type){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.type='sine';osc.frequency.setValueAtTime(type==='eat'?700:170,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(type==='eat'?1000:70,audio.currentTime+.12);gain.gain.setValueAtTime(.06,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);osc.start();osc.stop(audio.currentTime+.17);}catch{}}
function reset(){state=makeState();previous=state;progress=1;queued=null;runId=crypto.randomUUID();startedAt=0;$('#abort').disabled=true;$('#best').textContent=best??'-';overlay('READY','준비됐나요?','첫 방향 입력으로 출발합니다.\n벽과 몸을 피해 사과를 먹어 보세요.','다시 준비');$('#overlay-foot').textContent='방향키 또는 W A S D';$('#play').disabled=!profile;setSave('방향키를 눌러 출발하세요.');draw();game.focus({preventScroll:true});}
function startInput(name){if(!profile||!DIRECTIONS[name]||!['ready','running'].includes(state.mode))return;const d=DIRECTIONS[name];if(!allowed(state.direction,d)||queued)return;queued=d;if(state.mode==='ready'){state={...state,mode:'running'};$('#overlay').hidden=true;$('#abort').disabled=false;$('#play').disabled=true;startedAt=performance.now();lastFrame=startedAt;setSave('사과를 먹고 최고 기록을 만들어 보세요.');step();}}
function step(){previous=state;state=advance(state,queued||state.direction);queued=null;progress=0;if(state.mode==='collision'||state.mode==='win'){previous=state;progress=1;finish();}else if(state.ate)tone('eat');}
function frame(now){if(state.mode==='running'){const delta=lastFrame?now-lastFrame:0;lastFrame=now;if(delta>900){abort('화면이 오래 멈춰 현재 판을 중도 종료했어요. 기록은 저장하지 않습니다.');}else{progress+=delta/RULES.tickMs;while(progress>=1&&state.mode==='running'){const rest=progress-1;step();if(state.mode==='running')progress=rest;}draw();}}requestAnimationFrame(frame);}
function finish(){const endedBy=state.mode==='win'?'win':'collision',score=state.score;best=Math.max(best??0,score);$('#best').textContent=best;$('#abort').disabled=true;tone('end');overlay(endedBy==='win'?'BOARD COMPLETE':'GAME OVER',endedBy==='win'?'모든 칸을 채웠어요!':'이번 기록 '+score+'점','다시 시작해 나의 최고점에 도전해요.','다시 시작');$('#overlay-foot').textContent='방향키 또는 W A S D';const payload={runId,...profile,score,elapsedMs:Math.round(performance.now()-startedAt),ticks:state.ticks,endedBy,version:RULES.version};submitResult(payload);draw();}
function abort(message='중도 종료했습니다. 이 판의 기록은 저장하지 않습니다.'){if(!['ready','running'].includes(state.mode))return;state={...state,mode:'aborted',ate:false};previous=state;progress=1;queued=null;$('#abort').disabled=true;overlay('NOT SAVED','다음 도전을 기다려요','중도 종료한 판은 저장되지 않습니다.','다시 시작');setSave(message);draw();}
$('#student-form').addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const name=$('#student-name').value.trim().normalize('NFC'),id=$('#student-id').value.trim();if(!name||name.length>20||!/^\d{1,12}$/.test(id)){setSave('학번과 이름을 다시 확인해 주세요.','error');return;}profile={studentId:id,name,grade:Number($('#grade').value),classNo:Number($('#class-no').value)};best=null;$('#student-form').hidden=true;$('#profile-summary').hidden=false;$('#change-profile').hidden=false;$('#profile-name').textContent=name;$('#profile-detail').textContent=profile.grade+'학년 '+profile.classNo+'반 · '+id;$('#profile-label').textContent=name+' · '+profile.grade+'학년 '+profile.classNo+'반';$('#rank-grade').value=String(profile.grade);$('#rank-class').value=String(profile.classNo);reset();refreshRank();});
$('#change-profile').addEventListener('click',()=>{if(state.mode==='running'&&!confirm('학생 정보를 변경하면 현재 판을 중도 종료합니다. 계속할까요?'))return;if(state.mode==='running')abort();profile=null;best=null;state=makeState();previous=state;$('#student-form').hidden=false;$('#profile-summary').hidden=true;$('#change-profile').hidden=true;$('#profile-label').textContent='오늘의 최고 기록에 도전해요';$('#best').textContent='-';overlay('READY TO PLAY','길게 자라는 즐거움','학번과 이름을 확인하고\n게임을 시작해 보세요.','게임 시작');$('#play').disabled=true;draw();});
$('#play').addEventListener('click',reset);$('#abort').addEventListener('click',()=>abort());game.addEventListener('keydown',e=>{const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',a:'left',s:'down',d:'right'},key=e.key.length===1?e.key.toLowerCase():e.key;if(keys[key]){e.preventDefault();startInput(keys[key]);}else if(key==='Escape'){e.preventDefault();abort();}});game.addEventListener('pointerdown',e=>{if(e.target===canvas)game.focus({preventScroll:true});});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state.mode==='running')abort('탭을 벗어나 중도 종료했습니다. 기록은 저장하지 않습니다.');}else refreshRank();});
$('#sound').addEventListener('click',()=>{sound=!sound;$('#sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').setAttribute('aria-label',sound?'소리 끄기':'소리 켜기');if(sound)tone('eat');game.focus({preventScroll:true});});$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await game.requestFullscreen();game.focus();}catch{setSave('이 브라우저에서는 전체 화면을 사용할 수 없어요.');}});
function jsonp(action,params={}){return new Promise((resolve,reject)=>{if(!cfg.appsScriptUrl){reject(new Error('시트 연결 준비 중'));return;}const callback='__gajwaCb_'+Date.now()+'_'+sequence++,script=document.createElement('script');let timer;const cleanup=()=>{clearTimeout(timer);script.remove();delete window[callback];};window[callback]=data=>{cleanup();if(data?.ok)resolve(data);else reject(new Error(data?.message||'연결 오류'));};timer=setTimeout(()=>{cleanup();reject(new Error('응답 시간 초과'));},20000);script.onerror=()=>{cleanup();reject(new Error('시트 연결 실패'));};const url=new URL(cfg.appsScriptUrl);url.search=new URLSearchParams({action,...params,callback,t:String(Date.now())}).toString();script.src=url.href;script.referrerPolicy='no-referrer';document.head.appendChild(script);});}
function emptyRank(text){const td=document.createElement('td');td.colSpan=3;td.className='empty';td.textContent=text;const tr=document.createElement('tr');tr.appendChild(td);$('#rank-body').replaceChildren(tr);}
function renderRanks(entries){if(!entries.length){emptyRank('아직 기록이 없어요. 첫 기록을 만들어 보세요.');return;}const frag=document.createDocumentFragment();for(const r of entries){if(!Number.isInteger(Number(r.rank))||r.rank<1||r.rank>10)continue;const tr=document.createElement('tr');if(profile&&String(r.studentId)===profile.studentId&&Number(r.grade)===profile.grade&&Number(r.classNo)===profile.classNo){tr.className='my-row';best=Math.max(best??0,Number(r.score));$('#best').textContent=best;}const rank=document.createElement('td');rank.textContent=r.rank+'위';const who=document.createElement('td'),name=document.createElement('span'),detail=document.createElement('span');name.className='name';name.textContent=r.name;detail.className='student-detail';detail.textContent=r.grade+'학년 '+r.classNo+'반 · '+r.studentId;who.append(name,detail);const score=document.createElement('td');score.textContent=String(r.score);tr.append(rank,who,score);frag.appendChild(tr);}$('#rank-body').replaceChildren(frag);}
async function refreshRank(){if(document.hidden||rankingBusy)return;const epoch=requestEpoch;rankingBusy=true;try{const params=rankScope==='class'?{grade:$('#rank-grade').value,classNo:$('#rank-class').value}:{};if(profile){params.studentId=profile.studentId;params.studentGrade=String(profile.grade);params.studentClass=String(profile.classNo);}const result=await jsonp('leaderboard',params);if(epoch!==requestEpoch)return;renderRanks(result.entries||[]);$('#connection-dot').className='online';$('#rank-state').textContent='마지막 조회 '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(profile&&result.personalBest!==undefined){best=Math.max(best??0,Number(result.personalBest));$('#best').textContent=best;}}catch(err){if(epoch!==requestEpoch)return;$('#connection-dot').className='offline';$('#rank-state').textContent=(cfg.appsScriptUrl?'연결 지연 · 다음 조회에서 다시 시도합니다.':'구글 시트 연결 준비 중입니다.');if(!$('#rank-body .name'))emptyRank(cfg.appsScriptUrl?'연결을 확인하고 있어요.':'시트가 연결되면 학교 기록이 표시됩니다.');}finally{rankingBusy=false;if(epoch!==requestEpoch)refreshRank();}}
function chooseScope(scope){rankScope=scope;requestEpoch++;$('#all-rank').classList.toggle('selected',scope==='all');$('#class-rank').classList.toggle('selected',scope==='class');$('#all-rank').setAttribute('aria-pressed',String(scope==='all'));$('#class-rank').setAttribute('aria-pressed',String(scope==='class'));$('#rank-filters').hidden=scope!=='class';emptyRank('랭킹을 불러오는 중입니다.');refreshRank();}
$('#all-rank').addEventListener('click',()=>chooseScope('all'));$('#class-rank').addEventListener('click',()=>chooseScope('class'));for(const s of ['#rank-grade','#rank-class'])$(s).addEventListener('change',()=>{requestEpoch++;refreshRank();});
function postForm(payload){const frame=document.createElement('iframe'),form=document.createElement('form');frame.name='gajwa_save_'+payload.runId;frame.hidden=true;frame.title='구글 시트 저장 응답';form.action=cfg.appsScriptUrl;form.method='POST';form.target=frame.name;form.hidden=true;const input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify(payload);form.appendChild(input);document.body.append(frame,form);form.submit();setTimeout(()=>{form.remove();frame.remove();},60000);}
async function submitResult(payload){if(submitting.has(payload.runId))return;if(!cfg.appsScriptUrl){setSave('시트 연결 준비 중이라 이 기록은 저장되지 않았습니다.','error');return;}submitting.add(payload.runId);pending.set(payload.runId,payload);$('#retry-save').hidden=false;setSave('구글 시트에 기록을 저장하고 있어요.');for(let attempt=0;attempt<3;attempt++){try{postForm(payload);for(let n=0;n<6;n++){await new Promise(r=>setTimeout(r,1800+n*200));const result=await jsonp('status',{runId:payload.runId});if(result.found){pending.delete(payload.runId);submitting.delete(payload.runId);$('#retry-save').hidden=pending.size===0;if(runId===payload.runId)setSave('구글 시트 저장 완료 · 학교 랭킹이 갱신됩니다.','success');refreshRank();return;}}}catch{}if(runId===payload.runId)setSave('저장 응답이 늦어 같은 기록으로 재시도합니다.');}submitting.delete(payload.runId);if(runId===payload.runId)setSave('저장을 확인하지 못했어요. 연결을 확인해 주세요. 새로고침 전에 대기 기록을 다시 전송할 수 있습니다.','error');}
$('#retry-save').addEventListener('click',()=>{for(const p of pending.values())submitResult(p);});window.addEventListener('online',()=>{for(const p of pending.values())submitResult(p);refreshRank();});window.addEventListener('beforeunload',e=>{if(pending.size){e.preventDefault();e.returnValue='';}});window.addEventListener('resize',resizeCanvas);resizeCanvas();requestAnimationFrame(frame);refreshRank();setInterval(()=>refreshRank(),Math.max(5000,cfg.pollMs||5000));
// Read-only runtime metrics for development checks, no PII exposed here.
window.GAJWA_DEBUG=Object.freeze({getState:()=>({mode:state.mode,score:state.score,ticks:state.ticks,progress,head:routeForFrame(previous,state,progress).head}),getPendingCount:()=>pending.size});
